
-- ----------------------------
-- Table structure for MF_BAIDU_PAGE
-- ----------------------------
DROP TABLE "MODELFORM"."MF_BAIDU_PAGE";
CREATE TABLE "MODELFORM"."MF_BAIDU_PAGE" (
                                             "PAGEID" VARCHAR2(100 BYTE) NOT NULL,
                                             "BD_ID" VARCHAR2(100 BYTE)
)
    TABLESPACE "MODELFORMDB"
    LOGGING
    NOCOMPRESS
    PCTFREE 10
    INITRANS 1
    STORAGE (
    INITIAL 65536
    NEXT 1048576
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    BUFFER_POOL DEFAULT
            )
    PARALLEL 1
    NOCACHE
    DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of MF_BAIDU_PAGE
-- ----------------------------

-- ----------------------------
-- Table structure for MF_BAIDU_STATISTICS
-- ----------------------------
DROP TABLE "MODELFORM"."MF_BAIDU_STATISTICS";
CREATE TABLE "MODELFORM"."MF_BAIDU_STATISTICS" (
                                                   "BD_ID" VARCHAR2(100 BYTE) NOT NULL,
                                                   "BD_TIME" VARCHAR2(100 BYTE) NOT NULL,
                                                   "BD_WEBSITE" VARCHAR2(255 BYTE) NOT NULL,
                                                   "BD_DOMAIN" VARCHAR2(255 BYTE) NOT NULL,
                                                   "BD_MSG" VARCHAR2(255 BYTE),
                                                   "BD_STATISTICS_URL" VARCHAR2(255 BYTE) NOT NULL,
                                                   "BD_JS" VARCHAR2(500 BYTE) NOT NULL
)
    TABLESPACE "MODELFORMDB"
    LOGGING
    NOCOMPRESS
    PCTFREE 10
    INITRANS 1
    STORAGE (
    INITIAL 65536
    NEXT 1048576
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    BUFFER_POOL DEFAULT
            )
    PARALLEL 1
    NOCACHE
    DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of MF_BAIDU_STATISTICS
-- ----------------------------

-- ----------------------------
-- Table structure for MF_FIELD
-- ----------------------------
DROP TABLE "MODELFORM"."MF_FIELD";
CREATE TABLE "MODELFORM"."MF_FIELD" (
                                        "FIELD_ID" VARCHAR2(100 BYTE) NOT NULL,
                                        "FORM_ID" VARCHAR2(100 BYTE),
                                        "FIELD_TIME" VARCHAR2(100 BYTE),
                                        "FIELD_TYPE" VARCHAR2(1 BYTE),
                                        "FIELD_ZZ_TEST" VARCHAR2(255 BYTE),
                                        "FIELD_ZZ_DESC" VARCHAR2(255 BYTE),
                                        "FIELD_FILETYPE" VARCHAR2(1 BYTE),
                                        "FIELD_TIMETYPE" VARCHAR2(1 BYTE),
                                        "FIELD_NAME" VARCHAR2(255 BYTE),
                                        "FIELD_NAME_DESC" VARCHAR2(255 BYTE),
                                        "FIELD_SELECT_VALUE" VARCHAR2(100 BYTE)
)
    TABLESPACE "MODELFORMDB"
    LOGGING
    NOCOMPRESS
    PCTFREE 10
    INITRANS 1
    STORAGE (
    INITIAL 65536
    NEXT 1048576
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    BUFFER_POOL DEFAULT
            )
    PARALLEL 1
    NOCACHE
    DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of MF_FIELD
-- ----------------------------

-- ----------------------------
-- Table structure for MF_FORM
-- ----------------------------
DROP TABLE "MODELFORM"."MF_FORM";
CREATE TABLE "MODELFORM"."MF_FORM" (
                                       "FORM_ID" VARCHAR2(100 BYTE) NOT NULL,
                                       "FORM_NAME" VARCHAR2(255 BYTE),
                                       "FORM_TABLENAME" VARCHAR2(255 BYTE),
                                       "FORM_DESCRIBE" VARCHAR2(255 BYTE),
                                       "FORM_TIME" VARCHAR2(100 BYTE)
)
    TABLESPACE "MODELFORMDB"
    LOGGING
    NOCOMPRESS
    PCTFREE 10
    INITRANS 1
    STORAGE (
    INITIAL 65536
    NEXT 1048576
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    BUFFER_POOL DEFAULT
            )
    PARALLEL 1
    NOCACHE
    DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of MF_FORM
-- ----------------------------

-- ----------------------------
-- Table structure for MF_PAGE
-- ----------------------------
DROP TABLE "MODELFORM"."MF_PAGE";
CREATE TABLE "MODELFORM"."MF_PAGE" (
                                       "ID" VARCHAR2(100 BYTE) NOT NULL,
                                       "CTIME" VARCHAR2(100 BYTE) NOT NULL,
                                       "TITLE" VARCHAR2(255 BYTE),
                                       "MESSAGE" VARCHAR2(255 BYTE),
                                       "FORMID" VARCHAR2(100 BYTE) NOT NULL,
                                       "IMPORTSCRIPT" CLOB,
                                       "PAGETYPE" VARCHAR2(1 BYTE) NOT NULL,
                                       "CANUSE" VARCHAR2(1 BYTE) NOT NULL,
                                       "HTML_WIDTH" VARCHAR2(100 BYTE) NOT NULL,
                                       "PAGELIMIT" VARCHAR2(100 BYTE)
)
    TABLESPACE "MODELFORMDB"
    LOGGING
    NOCOMPRESS
    PCTFREE 10
    INITRANS 1
    STORAGE (
    INITIAL 65536
    NEXT 1048576
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    BUFFER_POOL DEFAULT
            )
    PARALLEL 1
    NOCACHE
    DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of MF_PAGE
-- ----------------------------

-- ----------------------------
-- Table structure for MF_PAGE_SET_ADD
-- ----------------------------
DROP TABLE "MODELFORM"."MF_PAGE_SET_ADD";
CREATE TABLE "MODELFORM"."MF_PAGE_SET_ADD" (
                                               "PAGEID" VARCHAR2(100 BYTE) NOT NULL,
                                               "FIELDID" VARCHAR2(100 BYTE) NOT NULL,
                                               "ISPOST" VARCHAR2(1 BYTE) NOT NULL,
                                               "FIELDSTATE" VARCHAR2(1 BYTE) NOT NULL,
                                               "DEFAULTVALUE" VARCHAR2(255 BYTE),
                                               "ORDERBY" VARCHAR2(100 BYTE)
)
    TABLESPACE "MODELFORMDB"
    LOGGING
    NOCOMPRESS
    PCTFREE 10
    INITRANS 1
    STORAGE (
    INITIAL 65536
    NEXT 1048576
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    BUFFER_POOL DEFAULT
            )
    PARALLEL 1
    NOCACHE
    DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of MF_PAGE_SET_ADD
-- ----------------------------

-- ----------------------------
-- Table structure for MF_PAGE_SET_LIST
-- ----------------------------
DROP TABLE "MODELFORM"."MF_PAGE_SET_LIST";
CREATE TABLE "MODELFORM"."MF_PAGE_SET_LIST" (
                                                "PAGEID" VARCHAR2(100 BYTE) NOT NULL,
                                                "FIELDID" VARCHAR2(100 BYTE) NOT NULL,
                                                "CAN_SORT" VARCHAR2(1 BYTE) NOT NULL,
                                                "CAN_SEARCH" VARCHAR2(1 BYTE) NOT NULL,
                                                "ORDERBY" VARCHAR2(100 BYTE)
)
    TABLESPACE "MODELFORMDB"
    LOGGING
    NOCOMPRESS
    PCTFREE 10
    INITRANS 1
    STORAGE (
    INITIAL 65536
    NEXT 1048576
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    BUFFER_POOL DEFAULT
            )
    PARALLEL 1
    NOCACHE
    DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of MF_PAGE_SET_LIST
-- ----------------------------

-- ----------------------------
-- Table structure for MF_VALUE
-- ----------------------------
DROP TABLE "MODELFORM"."MF_VALUE";
CREATE TABLE "MODELFORM"."MF_VALUE" (
                                        "FIELDID" VARCHAR2(100 BYTE) NOT NULL,
                                        "VALUE" VARCHAR2(255 BYTE)
)
    TABLESPACE "MODELFORMDB"
    LOGGING
    NOCOMPRESS
    PCTFREE 10
    INITRANS 1
    STORAGE (
    INITIAL 65536
    NEXT 1048576
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    BUFFER_POOL DEFAULT
            )
    PARALLEL 1
    NOCACHE
    DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of MF_VALUE
-- ----------------------------

-- ----------------------------
-- Primary Key structure for table MF_BAIDU_PAGE
-- ----------------------------
ALTER TABLE "MODELFORM"."MF_BAIDU_PAGE" ADD CONSTRAINT "SYS_C0011846" PRIMARY KEY ("PAGEID");

-- ----------------------------
-- Checks structure for table MF_BAIDU_PAGE
-- ----------------------------
ALTER TABLE "MODELFORM"."MF_BAIDU_PAGE" ADD CONSTRAINT "SYS_C0011845" CHECK ("PAGEID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "MODELFORM"."MF_BAIDU_PAGE" ADD CONSTRAINT "SYS_C0012002" CHECK ("PAGEID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table MF_BAIDU_STATISTICS
-- ----------------------------
ALTER TABLE "MODELFORM"."MF_BAIDU_STATISTICS" ADD CONSTRAINT "SYS_C0011854" PRIMARY KEY ("BD_ID");

-- ----------------------------
-- Checks structure for table MF_BAIDU_STATISTICS
-- ----------------------------
ALTER TABLE "MODELFORM"."MF_BAIDU_STATISTICS" ADD CONSTRAINT "SYS_C0011848" CHECK ("BD_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "MODELFORM"."MF_BAIDU_STATISTICS" ADD CONSTRAINT "SYS_C0011849" CHECK ("BD_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "MODELFORM"."MF_BAIDU_STATISTICS" ADD CONSTRAINT "SYS_C0011850" CHECK ("BD_WEBSITE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "MODELFORM"."MF_BAIDU_STATISTICS" ADD CONSTRAINT "SYS_C0011851" CHECK ("BD_DOMAIN" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "MODELFORM"."MF_BAIDU_STATISTICS" ADD CONSTRAINT "SYS_C0011852" CHECK ("BD_STATISTICS_URL" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "MODELFORM"."MF_BAIDU_STATISTICS" ADD CONSTRAINT "SYS_C0011853" CHECK ("BD_JS" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "MODELFORM"."MF_BAIDU_STATISTICS" ADD CONSTRAINT "SYS_C0012003" CHECK ("BD_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "MODELFORM"."MF_BAIDU_STATISTICS" ADD CONSTRAINT "SYS_C0012004" CHECK ("BD_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "MODELFORM"."MF_BAIDU_STATISTICS" ADD CONSTRAINT "SYS_C0012005" CHECK ("BD_WEBSITE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "MODELFORM"."MF_BAIDU_STATISTICS" ADD CONSTRAINT "SYS_C0012006" CHECK ("BD_DOMAIN" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "MODELFORM"."MF_BAIDU_STATISTICS" ADD CONSTRAINT "SYS_C0012007" CHECK ("BD_STATISTICS_URL" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "MODELFORM"."MF_BAIDU_STATISTICS" ADD CONSTRAINT "SYS_C0012008" CHECK ("BD_JS" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table MF_FIELD
-- ----------------------------
ALTER TABLE "MODELFORM"."MF_FIELD" ADD CONSTRAINT "SYS_C0011856" PRIMARY KEY ("FIELD_ID");

-- ----------------------------
-- Checks structure for table MF_FIELD
-- ----------------------------
ALTER TABLE "MODELFORM"."MF_FIELD" ADD CONSTRAINT "SYS_C0011855" CHECK ("FIELD_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "MODELFORM"."MF_FIELD" ADD CONSTRAINT "SYS_C0012009" CHECK ("FIELD_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table MF_FORM
-- ----------------------------
ALTER TABLE "MODELFORM"."MF_FORM" ADD CONSTRAINT "SYS_C0011858" PRIMARY KEY ("FORM_ID");

-- ----------------------------
-- Checks structure for table MF_FORM
-- ----------------------------
ALTER TABLE "MODELFORM"."MF_FORM" ADD CONSTRAINT "SYS_C0011857" CHECK ("FORM_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "MODELFORM"."MF_FORM" ADD CONSTRAINT "SYS_C0012010" CHECK ("FORM_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table MF_PAGE
-- ----------------------------
ALTER TABLE "MODELFORM"."MF_PAGE" ADD CONSTRAINT "SYS_C0011865" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table MF_PAGE
-- ----------------------------
ALTER TABLE "MODELFORM"."MF_PAGE" ADD CONSTRAINT "SYS_C0011859" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "MODELFORM"."MF_PAGE" ADD CONSTRAINT "SYS_C0011860" CHECK ("CTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "MODELFORM"."MF_PAGE" ADD CONSTRAINT "SYS_C0011861" CHECK ("FORMID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "MODELFORM"."MF_PAGE" ADD CONSTRAINT "SYS_C0011862" CHECK ("PAGETYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "MODELFORM"."MF_PAGE" ADD CONSTRAINT "SYS_C0011863" CHECK ("CANUSE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "MODELFORM"."MF_PAGE" ADD CONSTRAINT "SYS_C0011864" CHECK ("HTML_WIDTH" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "MODELFORM"."MF_PAGE" ADD CONSTRAINT "SYS_C0012011" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "MODELFORM"."MF_PAGE" ADD CONSTRAINT "SYS_C0012012" CHECK ("CTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "MODELFORM"."MF_PAGE" ADD CONSTRAINT "SYS_C0012013" CHECK ("FORMID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "MODELFORM"."MF_PAGE" ADD CONSTRAINT "SYS_C0012014" CHECK ("PAGETYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "MODELFORM"."MF_PAGE" ADD CONSTRAINT "SYS_C0012015" CHECK ("CANUSE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "MODELFORM"."MF_PAGE" ADD CONSTRAINT "SYS_C0012016" CHECK ("HTML_WIDTH" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table MF_PAGE_SET_ADD
-- ----------------------------
ALTER TABLE "MODELFORM"."MF_PAGE_SET_ADD" ADD CONSTRAINT "SYS_C0011869" PRIMARY KEY ("FIELDID");

-- ----------------------------
-- Checks structure for table MF_PAGE_SET_ADD
-- ----------------------------
ALTER TABLE "MODELFORM"."MF_PAGE_SET_ADD" ADD CONSTRAINT "SYS_C0011866" CHECK ("PAGEID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "MODELFORM"."MF_PAGE_SET_ADD" ADD CONSTRAINT "SYS_C0011867" CHECK ("ISPOST" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "MODELFORM"."MF_PAGE_SET_ADD" ADD CONSTRAINT "SYS_C0011868" CHECK ("FIELDSTATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "MODELFORM"."MF_PAGE_SET_ADD" ADD CONSTRAINT "SYS_C0012017" CHECK ("PAGEID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "MODELFORM"."MF_PAGE_SET_ADD" ADD CONSTRAINT "SYS_C0012018" CHECK ("FIELDID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "MODELFORM"."MF_PAGE_SET_ADD" ADD CONSTRAINT "SYS_C0012019" CHECK ("ISPOST" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "MODELFORM"."MF_PAGE_SET_ADD" ADD CONSTRAINT "SYS_C0012020" CHECK ("FIELDSTATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table MF_PAGE_SET_LIST
-- ----------------------------
ALTER TABLE "MODELFORM"."MF_PAGE_SET_LIST" ADD CONSTRAINT "SYS_C0011874" PRIMARY KEY ("FIELDID");

-- ----------------------------
-- Checks structure for table MF_PAGE_SET_LIST
-- ----------------------------
ALTER TABLE "MODELFORM"."MF_PAGE_SET_LIST" ADD CONSTRAINT "SYS_C0011870" CHECK ("PAGEID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "MODELFORM"."MF_PAGE_SET_LIST" ADD CONSTRAINT "SYS_C0011871" CHECK ("FIELDID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "MODELFORM"."MF_PAGE_SET_LIST" ADD CONSTRAINT "SYS_C0011872" CHECK ("CAN_SORT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "MODELFORM"."MF_PAGE_SET_LIST" ADD CONSTRAINT "SYS_C0011873" CHECK ("CAN_SEARCH" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "MODELFORM"."MF_PAGE_SET_LIST" ADD CONSTRAINT "SYS_C0012021" CHECK ("PAGEID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "MODELFORM"."MF_PAGE_SET_LIST" ADD CONSTRAINT "SYS_C0012022" CHECK ("FIELDID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "MODELFORM"."MF_PAGE_SET_LIST" ADD CONSTRAINT "SYS_C0012023" CHECK ("CAN_SORT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "MODELFORM"."MF_PAGE_SET_LIST" ADD CONSTRAINT "SYS_C0012024" CHECK ("CAN_SEARCH" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Checks structure for table MF_VALUE
-- ----------------------------
ALTER TABLE "MODELFORM"."MF_VALUE" ADD CONSTRAINT "SYS_C0011875" CHECK ("FIELDID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "MODELFORM"."MF_VALUE" ADD CONSTRAINT "SYS_C0012025" CHECK ("FIELDID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
